on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v.1.1
        with:
          src_dir: hub-homes
          dest_dir: hub-homes
          portal_id: ${{ secrets.HubSpotPortalId }}
          personal_access_key: ${{ secrets.HubSpotPersonalAccessKey }}
